apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  selector:
    app: driver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Match the containerPort from deployment.yaml
  type: LoadBalancer  # Change to ClusterIP or NodePort if needed

